INCLUDES += \
	$(SRC_DIR)/os/api \
	$(CFG_DIR)/os \

SOURCES += \
	$(SRC_DIR)/os/src/os.c \
	$(SRC_DIR)/os/src/os_timers.c \
	$(SRC_DIR)/os/src/os_tasks.c \
	$(SRC_DIR)/os/src/os_mem.c \
	$(SRC_DIR)/os/src/mem/simple_alloc.c \
	$(SRC_DIR)/os/src/mem/chunks_alloc.c \
	$(SRC_DIR)/os/src/mem/stdlib_alloc.c \
	$(SRC_DIR)/os/src/lists.c \
	$(CFG_DIR)/os/os_cfg.c \
