INCLUDES += \
	$(SRC_DIR)/gpio/api \
	$(SRC_DIR)/gpio/api/$(ARCH) \

SOURCES += \
	$(SRC_DIR)/gpio/src/gpio_ll.c \
	$(SRC_DIR)/gpio/src/$(ARCH)/port.c \

ifndef GPIO_LL
SOURCES += $(SRC_DIR)/gpio/src/gpio.c
endif
