INCLUDES += \
	$(SRC_DIR)/timer/api \
	$(SRC_DIR)/timer/api/$(ARCH) \

SOURCES += \
	$(SRC_DIR)/timer/src/timer_ll.c \
	$(SRC_DIR)/timer/src/$(ARCH)/timer_dev.c \

ifndef TIMER_LL
SOURCES += $(SRC_DIR)/timer/src/timer.c
SOURCES += $(SRC_DIR)/timer/src/$(ARCH)/timer_hal.c
endif
