#ifndef SRC_SERIAL_CFG_SERIAL_CFG_H_
#define SRC_SERIAL_CFG_SERIAL_CFG_H_

#define SERIAL_LINE_TERMINATOR '\r'
#define SERIAL_BAUD_RATE 19200U

#define SERIAL_ASYNC_RX ON
#define SERIAL_ASYNC_TX ON

// Only when Async TX is enabled
#define SERIAL_RECEIVE_BUFFER_LENGTH 256
#define SERIAL_RECEIVE_BUFFER_COUNT  2 // Double-buffered


#endif /* SRC_SERIAL_CFG_SERIAL_CFG_H_ */
