#ifndef SRC_SERIAL_CFG_SERIAL_CFG_H_
#define SRC_SERIAL_CFG_SERIAL_CFG_H_

#define SERIAL_LINE_TERMINATOR '\r'
#define SERIAL_RECEIVE_BUFFER_LENGTH 10
#define SERIAL_BAUD_RATE 19200

#endif /* SRC_SERIAL_CFG_SERIAL_CFG_H_ */
