INCLUDES += \
	$(SRC_DIR)/serial/api \
	$(SRC_DIR)/serial/api/$(ARCH) \
	$(CFG_DIR)/serial \

SOURCES += \
	$(SRC_DIR)/serial/src/serial.c \
	$(SRC_DIR)/serial/src/serial_ll.c \
	$(SRC_DIR)/serial/src/$(ARCH)/serial_ll.c \
