INCLUDES+=\
	$(SRC_DIR)/serial/api \
	$(CFG_DIR)/serial \

serial: \
	$(SRC_DIR)/serial/src/serial.o \
	$(SRC_DIR)/serial/src/serial_$(ARCH).o \
	$(SRC_DIR)/serial/src/serial_rx_async.o \
	$(SRC_DIR)/serial/src/serial_tx_async.o \
