#ifndef __SERIAL_TP_CFG__
#define __SERIAL_TP_CFG__

#define SERIAL_TP_REQUEST_HEADER        0xA0
#define SERIAL_TP_FRAME_TERMINATOR      0x0D
#define SERIAL_TP_REQUEST_BUFFER_LEN    32
#define SERIAL_TP_RESPONSE_BUFFER_LEN   32

#endif /* __SERIAL_TP_CFG__ */
