#ifndef SRC_SERIAL_TP_CFG_SERIAL_CFG_H_
#define SRC_SERIAL_TP_CFG_SERIAL_CFG_H_

#define SERIAL_TP_FRAME_TERMINATOR      0x0D
#define SERIAL_TP_RESPONSE_BUFFER_LEN   32

#endif /* SRC_SERIAL_TP_CFG_SERIAL_CFG_H_ */
