#ifndef SRC_SERIAL_CFG_SERIAL_CFG_H_
#define SRC_SERIAL_CFG_SERIAL_CFG_H_

#define SERIAL_BAUD_RATE 19200U

#define SERIAL_ASYNC_RX OFF
#define SERIAL_ASYNC_TX OFF

#if SERIAL_ASYNC_RX == ON
    #define SERIAL_RECEIVE_BUFFER_LENGTH 16
#endif

#endif /* SRC_SERIAL_CFG_SERIAL_CFG_H_ */
